name: Running strapi on minikube

on:
    push:
        branches: master


jobs:
    minikube-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: terraform init
              run: terraform init
              working-directory: ./terraform

            - name: terraform apply
              run: terraform apply --auto-approve
              working-directory: ./terraform
              env:
               AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
               AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Get artifact
              uses: actions/upload-artifact@v4
              with:
                name: terroform.tfstate state file 
                path: ./terraform/terraform.tfstate

